FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci --frozen-lockfile

COPY frontend . 

ENV NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_WS_URL=ws://localhost:8000
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]