FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copy ML pipeline
COPY ../ml /ml

RUN mkdir -p storage/structures storage/checkpoints cache/esmfold

EXPOSE 8000
