import os
import time
import hashlib
import json
import math
from typing import Optional
from dataclasses import dataclass


@dataclass
class StructurePrediction:
    plddt:      float
    pdb_string: str
    sequence:   str
    duration:   float


class ESMFoldWrapper:
    """
    Wrapper around ESMFold for protein structure prediction.

    In development mode: generates realistic simulated structures.
    In production mode: calls real ESMFold model.

    Set ESMFOLD_REAL=1 in environment to use real model.
    Requires: pip install fair-esm torch
    """

    def __init__(self, device: str = 'cpu', cache_dir: str = './cache/esmfold'):
        self.device = device
        self.cache_dir = cache_dir
        self.model = None
        self.use_real = os.environ.get('ESMFOLD_REAL', '0') == '1'

        os.makedirs(cache_dir, exist_ok=True)

        if self.use_real:
            self._load_model()
        else:
            print(
                '[ESMFold] Running in simulation mode. Set ESMFOLD_REAL=1 for real predictions.')

    def _load_model(self):
        """Load real ESMFold model. Requires ~16GB VRAM."""
        try:
            import esm
            import torch
            print('[ESMFold] Loading ESMFold v1 model...')
            self.model = esm.pretrained.esmfold_v1()
            self.model = self.model.eval()
            if self.device == 'cuda':
                self.model = self.model.cuda()
            print('[ESMFold] Model loaded successfully.')
        except ImportError:
            print('[ESMFold] fair-esm not installed. Falling back to simulation.')
            self.use_real = False
        except Exception as e:
            print(
                f'[ESMFold] Failed to load model: {e}. Falling back to simulation.')
            self.use_real = False

    def _cache_key(self, sequence: str) -> str:
        return hashlib.md5(sequence.encode()).hexdigest()

    def _load_cache(self, sequence: str) -> Optional[StructurePrediction]:
        key = self._cache_key(sequence)
        path = os.path.join(self.cache_dir, f'{key}.json')
        if os.path.exists(path):
            with open(path) as f:
                data = json.load(f)
            return StructurePrediction(**data)
        return None

    def _save_cache(self, sequence: str, pred: StructurePrediction):
        key = self._cache_key(sequence)
        path = os.path.join(self.cache_dir, f'{key}.json')
        with open(path, 'w') as f:
            json.dump({
                'plddt':      pred.plddt,
                'pdb_string': pred.pdb_string,
                'sequence':   pred.sequence,
                'duration':   pred.duration,
            }, f)

    def _simulate_prediction(self, sequence: str) -> StructurePrediction:
        """
        Simulated ESMFold prediction for development.
        Generates realistic pLDDT based on sequence properties
        and builds a proper alpha-helix PDB structure.
        """
        import random
        import numpy as np

        start = time.time()
        HYDROPHOBIC = set('VILMFYWCA')
        hydrophobic_frac = sum(
            1 for aa in sequence if aa in HYDROPHOBIC) / len(sequence)
        seed = int(hashlib.md5(sequence.encode()).hexdigest()[:8], 16)
        rng = random.Random(seed)
        base_plddt = 45 + hydrophobic_frac * 35
        plddt = base_plddt + rng.uniform(-8, 8)
        plddt = max(20.0, min(95.0, plddt))

        pdb = self._generate_helix_pdb(sequence, plddt)
        duration = time.time() - start + rng.uniform(0.5, 1.5)

        return StructurePrediction(
            plddt=round(plddt, 2),
            pdb_string=pdb,
            sequence=sequence,
            duration=round(duration, 3),
        )

    def _generate_helix_pdb(self, sequence: str, plddt: float) -> str:
        """Generate a valid alpha-helix PDB with real backbone coordinates."""
        AA_3LETTER = {
            'A': 'ALA', 'C': 'CYS', 'D': 'ASP', 'E': 'GLU', 'F': 'PHE',
            'G': 'GLY', 'H': 'HIS', 'I': 'ILE', 'K': 'LYS', 'L': 'LEU',
            'M': 'MET', 'N': 'ASN', 'P': 'PRO', 'Q': 'GLN', 'R': 'ARG',
            'S': 'SER', 'T': 'THR', 'V': 'VAL', 'W': 'TRP', 'Y': 'TYR',
        }

        lines = [
            'REMARK  Generated by RL-Fold ESMFold wrapper',
            f'REMARK  Mean pLDDT: {plddt:.2f}',
            f'REMARK  Sequence length: {len(sequence)}',
        ]

        atom_serial = 1
        rise = 1.5
        rot_deg = 100.0
        radius = 2.3

        for i, aa in enumerate(sequence.upper()):
            res_name = AA_3LETTER.get(aa, 'ALA')
            angle = math.radians(i * rot_deg)
            res_num = i + 1
            import random
            res_plddt = max(0, min(100, plddt + random.uniform(-8, 8)))

            atoms = [
                ('CA', radius * math.cos(angle),              radius *
                 math.sin(angle),              i * rise,         'C'),
                ('N',  radius * math.cos(angle + 0.5) - 1.2,  radius *
                 math.sin(angle + 0.5) - 1.2,  i * rise - 0.5,  'N'),
                ('C',  radius * math.cos(angle - 0.5) + 1.2,  radius *
                 math.sin(angle - 0.5) + 1.2,  i * rise + 0.5,  'C'),
                ('O',  radius * math.cos(angle + 1.0) + 2.0,  radius *
                 math.sin(angle + 1.0) + 2.0,  i * rise + 1.2,  'O'),
            ]

            for atom_name, x, y, z, element in atoms:
                lines.append(
                    f"ATOM  {atom_serial:5d} {atom_name:<4s} {res_name} A{res_num:4d}    "
                    f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00{res_plddt:6.2f}           {element}"
                )
                atom_serial += 1

        lines.extend(['TER', 'END'])
        return '\n'.join(lines)

    def _real_prediction(self, sequence: str) -> StructurePrediction:
        """Call real ESMFold model."""
        import torch

        start = time.time()
        with torch.no_grad():
            output = self.model.infer_pdb(sequence)

        plddt = float(self.model.infer(sequence)['mean_plddt'])
        duration = time.time() - start

        return StructurePrediction(
            plddt=round(plddt, 2),
            pdb_string=output,
            sequence=sequence,
            duration=round(duration, 3),
        )

    def predict(self, sequence: str, use_cache: bool = True) -> StructurePrediction:
        """
        Predict protein structure from amino acid sequence.
        Caches results to avoid redundant predictions.
        """
        sequence = sequence.upper().strip()

        # Check cache
        if use_cache:
            cached = self._load_cache(sequence)
            if cached:
                return cached
        if self.use_real and self.model is not None:
            pred = self._real_prediction(sequence)
        else:
            pred = self._simulate_prediction(sequence)
        if use_cache:
            self._save_cache(sequence, pred)

        return pred
